-- =====================================================================
-- SmartCart E-Commerce Platform
-- Database Definition: Tables Creation Script
-- Target Database: Oracle SQL / Oracle Database 19c/21c
-- =====================================================================

-- Drop existing tables in reverse dependency order to prevent FK constraints issues
BEGIN
    FOR t IN (
        SELECT table_name FROM user_tables 
        WHERE table_name IN (
            'SUPPORT_FEEDBACK', 'SUPPORT_TICKETS', 'PAYMENTS', 
            'ORDER_DETAILS', 'ORDERS', 'SHOPPING_CART', 
            'INVENTORY', 'PRODUCTS', 'CATEGORIES', 'USERS'
        )
    ) LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS';
    END LOOP;
END;
/

-- ---------------------------------------------------------------------
-- 1. USERS Table
-- Stores customer and administrative accounts
-- ---------------------------------------------------------------------
CREATE TABLE USERS (
    USER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FULL_NAME VARCHAR2(120) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(255) NOT NULL,
    PHONE VARCHAR2(30),
    ADDRESS VARCHAR2(300),
    ROLE VARCHAR2(20) DEFAULT 'customer' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT CHK_USERS_ROLE CHECK (ROLE IN ('customer', 'admin', 'manager'))
);

-- ---------------------------------------------------------------------
-- 2. CATEGORIES Table
-- Product catalog categorization
-- ---------------------------------------------------------------------
CREATE TABLE CATEGORIES (
    CATEGORY_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(100) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR2(500)
);

-- ---------------------------------------------------------------------
-- 3. PRODUCTS Table
-- Store items with pricing, category reference, and active status
-- ---------------------------------------------------------------------
CREATE TABLE PRODUCTS (
    PRODUCT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CATEGORY_ID NUMBER NOT NULL,
    PRODUCT_NAME VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(1000),
    PRICE NUMBER(10, 2) NOT NULL,
    IMAGE_URL VARCHAR2(500) NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_PRODUCTS_CATEGORY FOREIGN KEY (CATEGORY_ID) 
        REFERENCES CATEGORIES(CATEGORY_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_PRODUCTS_PRICE CHECK (PRICE >= 0),
    CONSTRAINT CHK_PRODUCTS_ACTIVE CHECK (IS_ACTIVE IN (0, 1))
);

-- ---------------------------------------------------------------------
-- 4. INVENTORY Table
-- Tracks on-hand stock quantities per product
-- ---------------------------------------------------------------------
CREATE TABLE INVENTORY (
    INVENTORY_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PRODUCT_ID NUMBER NOT NULL UNIQUE,
    STOCK_QUANTITY NUMBER DEFAULT 0 NOT NULL,
    LAST_UPDATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_INVENTORY_PRODUCT FOREIGN KEY (PRODUCT_ID) 
        REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_INVENTORY_STOCK CHECK (STOCK_QUANTITY >= 0)
);

-- ---------------------------------------------------------------------
-- 5. SHOPPING_CART Table
-- Active user shopping cart items
-- ---------------------------------------------------------------------
CREATE TABLE SHOPPING_CART (
    CART_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    QUANTITY NUMBER DEFAULT 1 NOT NULL,
    ADDED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_CART_USER FOREIGN KEY (USER_ID) 
        REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_CART_PRODUCT FOREIGN KEY (PRODUCT_ID) 
        REFERENCES PRODUCTS(PRODUCT_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_CART_QUANTITY CHECK (QUANTITY > 0)
);

-- ---------------------------------------------------------------------
-- 6. ORDERS Table
-- Customer purchase orders
-- ---------------------------------------------------------------------
CREATE TABLE ORDERS (
    ORDER_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    TOTAL_AMOUNT NUMBER(10, 2) NOT NULL,
    ORDER_STATUS VARCHAR2(30) DEFAULT 'Pending' NOT NULL,
    CONSTRAINT FK_ORDERS_USER FOREIGN KEY (USER_ID) 
        REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_ORDERS_AMOUNT CHECK (TOTAL_AMOUNT >= 0),
    CONSTRAINT CHK_ORDERS_STATUS CHECK (
        ORDER_STATUS IN ('Pending', 'Processing', 'Shipped', 'Delivered', 'Cancelled')
    )
);

-- ---------------------------------------------------------------------
-- 7. ORDER_DETAILS Table
-- Line items associated with customer orders
-- ---------------------------------------------------------------------
CREATE TABLE ORDER_DETAILS (
    DETAIL_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    PRICE NUMBER(10, 2) NOT NULL,
    CONSTRAINT FK_DETAILS_ORDER FOREIGN KEY (ORDER_ID) 
        REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_DETAILS_PRODUCT FOREIGN KEY (PRODUCT_ID) 
        REFERENCES PRODUCTS(PRODUCT_ID),
    CONSTRAINT CHK_DETAILS_QUANTITY CHECK (QUANTITY > 0),
    CONSTRAINT CHK_DETAILS_PRICE CHECK (PRICE >= 0)
);

-- ---------------------------------------------------------------------
-- 8. PAYMENTS Table
-- Transaction records linked to orders
-- ---------------------------------------------------------------------
CREATE TABLE PAYMENTS (
    PAYMENT_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ORDER_ID NUMBER NOT NULL,
    PAYMENT_METHOD VARCHAR2(50) NOT NULL,
    PAYMENT_STATUS VARCHAR2(30) DEFAULT 'Pending' NOT NULL,
    PAYMENT_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_PAYMENTS_ORDER FOREIGN KEY (ORDER_ID) 
        REFERENCES ORDERS(ORDER_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_PAYMENTS_STATUS CHECK (
        PAYMENT_STATUS IN ('Pending', 'Completed', 'Failed', 'Refunded')
    )
);

-- ---------------------------------------------------------------------
-- 9. SUPPORT_TICKETS Table
-- Customer service and order inquiry tickets
-- ---------------------------------------------------------------------
CREATE TABLE SUPPORT_TICKETS (
    TICKET_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    USER_ID NUMBER NOT NULL,
    ORDER_ID NUMBER,
    ISSUE_TYPE VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(1000) NOT NULL,
    STATUS VARCHAR2(30) DEFAULT 'Open' NOT NULL,
    PRIORITY VARCHAR2(20) DEFAULT 'Medium' NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_TICKETS_USER FOREIGN KEY (USER_ID) 
        REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_TICKETS_ORDER FOREIGN KEY (ORDER_ID) 
        REFERENCES ORDERS(ORDER_ID) ON DELETE SET NULL,
    CONSTRAINT CHK_TICKETS_STATUS CHECK (STATUS IN ('Open', 'In Progress', 'Resolved', 'Closed')),
    CONSTRAINT CHK_TICKETS_PRIORITY CHECK (PRIORITY IN ('Low', 'Medium', 'High', 'Urgent'))
);

-- ---------------------------------------------------------------------
-- 10. SUPPORT_FEEDBACK Table
-- Ratings and customer feedback on resolved tickets
-- ---------------------------------------------------------------------
CREATE TABLE SUPPORT_FEEDBACK (
    FEEDBACK_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TICKET_ID NUMBER NOT NULL UNIQUE,
    RATING NUMBER(1) NOT NULL,
    COMMENTS VARCHAR2(1000),
    CONSTRAINT FK_FEEDBACK_TICKET FOREIGN KEY (TICKET_ID) 
        REFERENCES SUPPORT_TICKETS(TICKET_ID) ON DELETE CASCADE,
    CONSTRAINT CHK_FEEDBACK_RATING CHECK (RATING BETWEEN 1 AND 5)
);

-- Create performance indexes for frequent lookups
CREATE INDEX IDX_USERS_EMAIL ON USERS(EMAIL);
CREATE INDEX IDX_PRODUCTS_CAT ON PRODUCTS(CATEGORY_ID);
CREATE INDEX IDX_ORDERS_USER ON ORDERS(USER_ID);
CREATE INDEX IDX_CART_USER ON SHOPPING_CART(USER_ID);
CREATE INDEX IDX_TICKETS_USER ON SUPPORT_TICKETS(USER_ID);

COMMIT;
